### ISSUE TITLE
🚦 [Code Review] 조성열

### ISSUE THREAD

**Issue by ryanjoe02** [likelion-backend-6th/TrackProject_1_ChoiSeonWoo#34]
## 코드리뷰
- common 디렉토리 안에 user와 post앱에서 중복된 models.py 과 permissions.py를 작성하여 중복코드를 줄인 부분이 인상깊었습니다. 

- permissions.py을 이용해서 API 뷰에 적용하면, API 엔드포인트에 대한 요청이나 객체에 대한 액션을 할 때 마다 권한을 체크하는 함수를 잘 봤습니다

## 개선 할 점

- test.py 안 MagicMock 부분에서 파일 자체를 불러와  "common.utils"  으로 테스트를 해보는 것이 좋을거 같습니다.

**Comment by 25th-Night** [comment]
좋은 리뷰 감사합니다. :)
남은 2차 프로젝트도 화이팅입니다!
