### ISSUE TITLE
🏳‍🌈 [Code Review] 한승훈

### ISSUE THREAD

**Issue by CloudFlavorKettle** [likelion-backend-6th/TrackProject_1_ChoiSeonWoo#35]
```좋았던 점```
- 프로필 같은 추가적인 기능을 고민하셨다는게 좋았습니다.
- 많은 노력을 기울이신게 보여서 좋았습니디.
- 문서도 깔끔하게 정리되어 있어서 좋았습니다. 이해에 많은 도움이 될 것 같네요.

**Comment by 25th-Night** [comment]
좋은 리뷰 감사합니다. :)
남은 2차 프로젝트도 화이팅입니다!
