### ISSUE TITLE
[Code Review] 전예진

### ISSUE THREAD

**Issue by yaezzin** [likelion-backend-6th/TrackProject_1_ChoiSeonWoo#36]
* 주어진 요구 사항 외에도 많은 기능을 담으시고, 코드에 많은 고민을 하신게 나타나서 좋았습니다.
* 또한 리드미에서도 프로젝트의 개요 및 진행 상황들이 잘 나타나서 많은 참고가 될 것 같습니다.
* 코드를 읽어보고 궁금한 점은 따로 코멘트 남기겠습니다. : )

**Comment by 25th-Night** [comment]
좋은 리뷰 감사합니다. :)
남은 2차 프로젝트도 화이팅입니다!
